server:
  port: 8083


#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8084/eureka  # Replace with your Eureka server's host and port
#  instance:
#    prefer-ip-address: true  # Register with the IP address of the instance


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/HotelMicroservices
    username: postgres
    password: root
  application:
    name: HOTEL-SERVICE
  config:
      import:
        - configserver:http://localhost:8086


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true




okta:
  oauth2:
    issuer: https://dev-36615249.okta.com/oauth2/default
    audience: api://default



